### ISSUE TITLE
Implement a 10 foot display mode

### ISSUE THREAD

**Issue by OonihiloO** [nihilux-org/roon-web-stack#23]
From the users feedback, the display of the APP on TV is not great: texts are too small to be easily readable.

As a 10 foot client, is, form a browser point of view, just another desktop (media queries won't help), and that the concept of display mode has been introduced (to support the compact and the wide mode at first), this seem to be the easy way to go.

As a `roon-web-stack` user, I want to have a readable and nice display on TV, with an easy setup.
As a `roon-web-stack` maintainer, I want to ensure that display mode versatility scalable, as it's one of the core motivation for this project.

**Comment by arthursoares** [comment]
First of kudos on the initiative. I'm interested in contributing to the project, as a product manager with limited coding experience. 

Do you have some references or inspiration for the 100ft mode? I agree with you that it is a big difference to the regular view in other devices. A TV interface tends to be a lot more passive than interactive.

**Comment by arthursoares** [comment]
@OonihiloO That would be great. Let me know how I can collaborate :)

**Comment by arthursoares** [comment]
@OonihiloO I quickly tested running the `docker` image with the beta tag, but it failed to run on my system (x86/64)

```
standard_init_linux.go:230: exec user process caused: exec format error
```

If you want to point to a sha, I can also build and run locally :)

**Comment by arthursoares** [comment]
@OonihiloO hello! Sorry for the absence, I'm preparing for a month holiday, and was caught up with some work handover! I look forward to test it on Sunday when I'm back in Berlin.

**Comment by arthursoares** [comment]
Hello @OonihiloO, I finally came back from holidays and spent some time getting my personal machine back with a development workspace. I've managed to build and run locally the latest at `main`. Is there a specific behavior to trigger the 10ft Display Mode? Are you filtering by resolution or WebAgent? This is where I'm currently at.

![CleanShot 2024-08-29 at 22 47 28@2x](https://github.com/user-attachments/assets/45c5dd4b-17db-4cbf-8b04-467836d287d5)

**Comment by arthursoares** [comment]
Hi @OonihiloO,

First off, I wanted to thank you for sharing this project and for all the hard work you've put into it. I finally had the chance to fully explore it, and I must say, my initial impressions are very positive. The feature looks and works amazingly well, especially for a beta version. I didn't encounter any bugs during my use (though I wasn't specifically testing for them), so kudos on a solid build!

I wanted to share some general thoughts and suggestions based on my use case, which might be useful as you continue development:

**My Use Case:**

I'm using the software on a Raspberry Pi (or iPad) connected to a display with an external DAC. My setup is quite simple—I primarily use it as a display to monitor what's currently playing (Album Art + Track / Artist information).

**General Feedback**:

**Display Format**:

Since I'm using a 16:9 or 16:10 display, I noticed that this format doesn't make the best use of the square album artwork. Adding some space or padding around the main frame could improve the visual experience.

A design approach similar to Apple Music on Apple TV could be inspiring. They use a blurred background gradient derived from the album art, which looks aesthetically pleasing and enhances the overall visual experience.

**Track Meta Display**:

I found the superimposition of the track metadata (Title + Artist) over the album art a bit distracting. Depending on the track, this can cover a significant portion of the artwork.
Perhaps dedicating a separate space for this information, rather than overlaying it on the album art, could make for a cleaner and more user-friendly design.

**Visual References**:

I'll add a couple of images to illustrate what I mean more clearly. I hope these can be helpful for future design tweaks. 

Thank you for your efforts on this project. I'm excited to see how it evolves and would be happy to continue providing feedback if that would be useful.

- https://www.apple.com/newsroom/images/product/apple-music/Apple-Music-Sing-hero_big.jpg.large.jpg
- https://www.reddit.com/media?url=https://preview.redd.it/tvos-16-2-new-apple-music-now-playing-interface-v0-8t1xz4ukwk4a1.jpg?width%3D1080%26crop%3Dsmart%26auto%3Dwebp%26s%3D8d3a9ddf45cde118868d5975b02c6b6c022f4e5d
- https://www.reddit.com/media?url=https://preview.redd.it/tvos-16-2-new-apple-music-now-playing-interface-v0-i8zw35ukwk4a1.jpg?width%3D4032%26format%3Dpjpg%26auto%3Dwebp%26s%3D44cbebaddb814516457f5400b65b09d38d755387

**Comment by arthursoares** [comment]
@OonihiloO I've been using the 10ft mode over the last days in my setup, and it has been a great addition. I replaced the RPi case that had a Display and was running Roopie for another distro in which I could run the Raspberry with an external display.

![IMG_6804](https://github.com/user-attachments/assets/d4b84c66-83a6-4c48-a05d-7b5dd7abae6a)

Do you plan on making the 10ft display available on the repo for further customizations? I'm looking forward to make some tweaking and experiments with it.

**Comment by arthursoares** [comment]
Thank you, @OonihiloO! I once again updated things on my side and made some small tweaks. This is working great! I will take a look at the other tickets, and see if I can contribute to something.

![ScreenShot 2024-12-02 at 10 01 06 -@2x](https://github.com/user-attachments/assets/9ec4be29-e163-43e9-a104-713a346864f9)
